name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
