name: release-publish

permissions:
  contents: read
  pages: write
  id-token: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.14"

      - name: Configure Pages
        uses: actions/configure-pages@v6

      - name: Build documentation
        run: uv run yeet scripts/build_docs.py --clean

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: site

  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env
        with:
          python-version: "3.14"

      - name: Build distributions
        run: uv build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: uvx twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
